version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/hit-me-please
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv ENV
            . ENV/bin/activate
            pip install -r requirements.txt
            pip install ansible
      - run:
          name: run unit tests
          command: |
            . ENV/bin/activate
            cd hit_me_please && python manage.py test
      - run:
          name: build and push image
          command: |
            docker build -t prontobacon/hitme:live .
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            docker push prontobacon/hitme:live
      - add_ssh_keys:
          fingerprints:
            - "e4:2b:66:70:d2:c3:00:6d:5a:12:16:54:04:17:4e:8d"
      - run:
          name: deploy
          command: |
            . ENV/bin/activate
            cd ansible
            ansible-playbook -i hosts deploy.yml --extra-vars "project_path=~/hit-me-please username=bacon"

